body of the portfolio
yahyaelganyni1/mobile-version-skeleton pull request #2
Opened 2021-06-04 15:06 UTC by yahyaelganyni1

For the rest of the body of the portfolio project, I added the cards of my projects to a CSS grid container, and for every card, I used a flexbox  container, and the about  me I used flexbox

2021-06-04 15:58 UTC, Temmarie requested changes
## STATUS: CHANGES REQUIRED! :recycle:

### Hi @yahyaelganyni1     ! :wave: :wave:

#### You have done really well in implementing the requirements.
- You used proper GitHub Flow ✔️ 
- Your README and PR message are descriptive ✔️ 

 However, there are changes required for you to make in order for this project to be approved. 

> Keep in mind that your long hours of work are appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. :smile:

- - -

### **Required Changes** ♻️
_See the inline comments below for the required changes_


### Optional Changes 👌
Every comment with the OPTIONAL prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend that you take them into account as they can make your code better.
- Consider using[ Font Awesome](https://fontawesome.com/v4.7/icons/) icons for your project instead of images.

_If anything doesn't seem clear to you, feel free to leave your question or comment in the PR thread below_

**_"Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise."_**
- - - 
**Note that you still have 2 more reviews as written in the [Code Reviews Limit Policy](https://microverse.zendesk.com/hc/en-us/restricted?return_to=https%3A%2F%2Fmicroverse.zendesk.com%2Fhc%2Fen-us%2Farticles%2F1500004088561), however, if you feel this review is unfair, you can request a second opinion using [this](https://airtable.com/shrQAqnBwek5a0O0s) form.**

__Kindly make the necessary changes and submit another code review request.__

2021-06-04 15:58 UTC, Temmarie commented on index.html
> +    <section class="midel-part">
- [ ] The main container of the projects should use `display:grid`.
In order to layout the elements in the `Works` section you should use CSS Grid and Flexbox combined (it is mandatory that you use both). Use **CSS Grid** in the main container that contains all of the cards and use **Flexbox** to layout an individual card.

2021-06-04 15:58 UTC, Temmarie commented on style.css
> +}
- [ ] You must stick to the design as much as possible (e.g., font, colours, images, tests, margins) using the templates in Figma. Fix this style to reduce the distance between the `My recent works` and the social media links from the headline.

**Original** | **Your clone**
  ----------- | -----------
 ![image](https://user-images.githubusercontent.com/49621279/120825618-69ca1f00-c50e-11eb-99e9-fd546d4f41ad.png) | ![image](https://user-images.githubusercontent.com/49621279/120825801-9aaa5400-c50e-11eb-93ec-c1b8ef823369.png)

2021-06-04 15:58 UTC, Temmarie commented on index.html
> +      </section>
- [ ] Instead of using a `<div class="the-cards">` to group all the projects, use a `section` instead.

- [ ] The list of projects should be grouped using a `ul` tag to group them, and `li` per project as it orders the element semantically making it obvious to screen readers or assistive technologies to know they belong to the same group, this helps with proper accessibility. Kindly make this change and submit it for review.

- [ ] The main container of the projects should use `display:grid`.
In order to layout the elements in the `Works` section you should use CSS Grid and Flexbox combined (it is mandatory that you use both). Use **CSS Grid** in the main container that contains all of the cards and use **Flexbox** to layout an individual card.

2021-06-04 15:58 UTC, Temmarie commented on index.html
> +      </section>
- [x] - [ ] I see that you have grouped the list of technologies (e.g., "JavaScript", "HTML" and "CSS") under each category using `ul` -`li`, good job there!
- [x] Like I earlier said: You must stick to the design as much as possible (e.g., font, colours, images, tests, margins) using the templates in Figma. Look out for the `width, margin, height` of this card.
- [x] Note that this image of your clone was taken at a screen size of 483px, when I reduced it to be about the same size as the original, elements were popping out of place.

**Original** | **Your clone**
  ----------- | -----------
 ![image](https://user-images.githubusercontent.com/49621279/120827324-2f618180-c510-11eb-93cb-5022e9930de1.png) | ![image](https://user-images.githubusercontent.com/49621279/120827791-a8f96f80-c510-11eb-8e34-fa9a938c27c0.png)

2021-06-04 15:58 UTC, Temmarie commented on index.html
> +    </section>
- [ ] You are currently missing the background image for this section. It should have the proper background image (decorations are always background images, not `img` tags).

- [ ] The `Get my Resume` button has a border that is not in the original. Kindly remove it.
**Original** | **Your clone**
  ----------- | -----------
  ![image](https://user-images.githubusercontent.com/49621279/120828820-d4308e80-c511-11eb-9a63-5ec76ef97a37.png) | ![image](https://user-images.githubusercontent.com/49621279/120829137-fde9b580-c511-11eb-82b1-3f373f51d86f.png)

2021-06-04 15:58 UTC, Temmarie commented on index.html
> +    </section>
- [ ] I see that you have grouped the list of technologies (e.g., "JavaScript", "HTML" and "CSS") under each category using `ul` -`li`, good job there! However, the categories (languages, Frameworks, Skills) themselves should be grouped using `ul` - `li` as well.  
 - [ ] Also, look up the styling for this section, you are missing the border for the card.
 _Refer to my comments on design above._

2021-06-05 01:43 UTC, MahmoudBakr23 requested changes
Hi @yahyaelganyni1😃, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

> Keep in mind that your long hours of work are appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. 😄

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [ ] **OPTIONAL** You've got a nice README, but it'd be even nicer if you used the README [template](https://github.com/microverseinc/readme-template).
It's so important that your projects look professional and good-looking.

_Check the **OPTIONAL** comments under the review._

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-05 01:43 UTC, MahmoudBakr23 commented on index.html
> +
- [ ] **OPTIONAL** Please keep in mind not to leave any extra blank lines or indentations to keep and remain your code clean and organized.
_We only add blank lines and indentations when there's a good reason for that, such as separating two logical pieces of code or two large sections apart._

And probably the reason this line here is that you missed something at the Linter's configuration. So, kindly consider the following.

- [ ] **OPTIONAL** If you look at the `.github` directory at the top of the repo's files, you'll find out that you missed adding the 'workflows' directory first. Please give yourself a reminder on how to correctly set up the [Linter](https://github.com/microverseinc/linters-config/tree/master/html-css) because of three important reasons:
1- To keep your code clean and professional
2- It's nearly impossible to review a code that hasn't get checked by the Linter because of the styling errors that might make the reviewer confused about the code. 
3- This could make your repo gets invalidated.

_Please make sure that every project is checked by Linter and all the checks are passing._

> I'm sorry this point didn't show up for you in the earlier review.

2021-06-05 01:43 UTC, MahmoudBakr23 commented on index.html
> +        <div class="card">
- [ ] As the previous reviewer asked you in the first review. Please make sure to wrap all the projects' cards inside a `<ul>` tag with `<li>` tags for every single card (project). Let's work on that 👍

2021-06-05 01:43 UTC, MahmoudBakr23 commented on index.html
> +            <ul>
- [ ] The icon for the "Frameworks" category needs a few modifications in the styling. Kindly look at the image of your project down below, then apply the corresponding changes.
> This is on 430px width so it's a mobile screen.
![Screenshot](https://user-images.githubusercontent.com/47625407/120876186-9124f880-c5af-11eb-8dcd-a974d0df5bae.png)

2021-06-05 08:47 UTC, yahyaelganyni1 commented on index.html
> +        <div class="card">
why do I have to do that? it's not a good practice its cards not a list of something

2021-06-05 08:50 UTC, yahyaelganyni1 commented on index.html
> +            <ul>
I don't understand what should I wrap inside what?

2021-06-05 09:08 UTC, MahmoudBakr23 commented on index.html
> +        <div class="card">
It's a list of all the projects (each project is an element within that list) in your portfolio, and it's a good practice because it'll save extra lines of code and help to optimize the website.
**Also, it's a requirement in this project!**

2021-06-05 09:17 UTC, MahmoudBakr23 commented on index.html
> +            <ul>
You should list all the categories in a `<ul>` tag, and inside each element (category) of that list is a `<li>` tag that will have another (smaller) `<ul>` tag list inside of it that contains the `<li>` tags of (i.e. Html, CSS, javascript, etc).

2021-06-05 09:24 UTC, henatan99 commented on index.html
> +        <div class="card">
- [ ] This issue is not addressed! @yahyaelganyni1 , you are right it is a cards section, but the `section` tag is most of the time used for distinguishing different unrelated contents in a page. Here, you are listing your projects to showcase in the portfolio. In some circumstances `article` would be a good semantic tag. But for this particular elements `li` items in `ul` tag is more semantically fit. 
- [ ] I also advise you to make requested changes even if you have doubts and reach out Microverse through the link provided in the review summary.

2021-06-05 09:31 UTC, henatan99 commented on index.html
> +            <ul>
@yahyaelganyni1, You could have made all the `languages` class elements `li` elements and wrap them in a `ul` tag. The requested changes are not addressed well!

2021-06-05 09:43 UTC, henatan99 requested changes
Hi @yahyaelganyni1 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
- [x] I am sorry, I haven't seen a linter check report in your PR (Pull request). A professional repo always has passed linter check reports. 
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-05 09:43 UTC, henatan99 commented on index.html
> +          <section class="card-container">
- [ ] The section tag is most of the time used for distinguishing different unrelated and relatively big contents in a page. Here, you are listing your projects to showcase in the portfolio. In some circumstances, `article` would be a good semantic tag. But for these particular elements, `li` items in ul tag are more semantically fit.
- [ ] I also advise you to make requested changes even if you have doubts and reach out to Microverse through the link provided in the review summary.

2021-06-05 09:43 UTC, henatan99 commented on index.html
> +              <div class="the-Languages">
@yahyaelganyni1, You could have made all the `languages` class elements `li` elements and wrap them in a `ul` tag, for the same reason raised in the other comment.

2021-06-05 13:08 UTC, teekaytech approved these changes
## Status: Approved :green_circle: 

### Congratulations @yahyaelganyni1 :tada: :clinking_glasses: 

**Your project is complete!  This is a convenient point to merge :rocket:**

**Comment(s)**
- Please, always try to implement all project requirements after the second review. As you know, there's this golden rule that you have a maximum of 3 reviews per project. This means that your project must be approved by the third reviewer, at most. Next time this happens, you might be asked to repeat the project. Kindly take note.
- - - - - -

**_Feel free to leave any questions or comments in the PR thread if something is not 100% clear._**

Do not forget to fill the project completion form, as this is important for your weekly progress score.

**_Good luck with your next task._**

* * * 
_Cheers,_
**[Taofeek Olalere](https://github.com/teekaytech)**
__Happy Coding :smiley:__

2021-06-09 15:08 UTC, merged